import React from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { log } from "thetajs";

export default function Home() {
  const [answer, setAnswer] = React.useState<number>();

  const calculateLog = (input: string): void => {
    const logarithmCalculation: number = log(parseInt(input));
    setAnswer(logarithmCalculation);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">LogCalc</a>
        </h1>

        <p className={styles.description}>
          Get started by inserting an expression below.
        </p>

        <input
          onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
            calculateLog(e.target.value)
          }
        />
        <p>
          {Number.isNaN(answer) || answer === undefined
            ? "The input is either blank or invalid to be part of a logarithmic expression! Plaese try again."
            : `Real-time answer: ${answer}`}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
